# Generated by Django 5.1.2 on 2024-10-12 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShahkarModelBasic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ShahkarModelIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=50)),
                ('year_2', models.IntegerField(blank=True, null=True)),
                ('month_2', models.IntegerField(blank=True, null=True)),
                ('basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shahkar_income_details', to='shahkar.shahkarmodelbasic')),
            ],
        ),
    ]
